Migrating code to show bike parking spaces as a vector layer
stadtnavi/digitransit-ui pull request #423
Opened 2021-05-10 11:22 UTC by jpidelatorre

## Proposed Changes

  -

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform

closes #

2021-05-10 12:16 UTC, leonardehrenfried commented
This is a work in progress but here are my requests:

- Resolve merge conflicts
- Use the compilation script to add the icons: https://github.com/stadtnavi/digitransit-ui/blob/next/docs/Icons.md
- Make the black dots at high zoom level also blue
- Add `SelectBikeParkRow`: https://github.com/stadtnavi/digitransit-ui/blob/master/app/component/map/tile-layer/SelectBikeParkRow.js

2021-05-11 12:33 UTC, leonardehrenfried commented on static/assets/svg-sprite.hb-source.svg
> +    <symbol id="icon-icon_city`withoutBox" viewBox="0 0 283.46 283.46">
I think this was an accident, isn't it?

2021-05-12 07:29 UTC, leonardehrenfried commented
@jpidelatorre Are you blocked here?

2021-05-12 07:57 UTC, jpidelatorre commented
> @jpidelatorre Are you blocked here?

Sorry, Leonard, I didn't read your comment. I was not blocked, I was solving some merging conflicts.
I think the latest code is working properly.

2021-05-12 08:48 UTC, leonardehrenfried commented
Great, checking it.

2021-05-12 08:55 UTC, leonardehrenfried requested changes
The latest version of this PR doesn't show any bike parking facilities on the map. Please read my comment.

2021-05-12 08:55 UTC, leonardehrenfried commented on app/component/map/tile-layer/VectorTileLayerContainer.js
> +      if (config.bikeParks && config.bikeParks.show) {
You need to change this code to take the new variable name `layersToAdd` into account. Also, please remove the code about dynamic parking lots from this PR.

2021-05-12 11:53 UTC, merged

2021-05-12 11:53 UTC, leonardehrenfried commented
Thanks