Harmonize vehicle rental messages
stadtnavi/digitransit-ui pull request #774
Opened 2021-10-19 11:46 UTC by hbruch

## Proposed Changes
This PR harmonizes various vehicle rental messages, e.g. by renaming bike / cycle to citybike in bikesharing context. 

Further more, it uses network configuration property `type` (which should be refactored in future to map to GBFS vehicle formFactor) to select appropriate messages.

It might make sense to add an operator name to the user facing messages as well as distinguishing between stations and free floating vehicles. This PR does not address this yet.

Note: this WIP PR has a temporary network-renaming patch in `CityBike.js` which is not intended to be merged.

## Pull Request Check List

  - A reasonable set of unit tests is included
  - Console does not show new warnings/errors
  - Changes are documented or they are self explanatory
  - This pull request does not have any merge conflicts
  - All existing tests pass in CI build
  - Code coverage does not decrease (unless measured incorrectly)

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform
  - Check that the implementation matches the design, when such one is defined in a Jira issue
  - Merge the pull request

2021-10-19 11:59 UTC, leonardehrenfried commented on app/configurations/config.landstadtmobil.js
> +            'tier-reutlingen': {
Are you sure the hypen is correct? The system id is "tier_REUTLINGEN" which is being lowercased.

2021-10-20 12:08 UTC, leonardehrenfried requested changes
For me the citybike icons don't show up. Do they for you?

I see the following errors in the console:
![Screenshot from 2021-10-20 14-03-00](https://user-images.githubusercontent.com/151346/138089700-81b8da75-80e5-45c6-ba20-8949d57a5cdc.png)

Also, there are linting errors which make the CI fail.

2021-10-20 12:10 UTC, leonardehrenfried commented on app/configurations/config.landstadtmobil.js
> +            'tier-reutlingen': {
![Screenshot from 2021-10-20 14-09-42](https://user-images.githubusercontent.com/151346/138089948-00eba3e6-fa92-4354-94e3-bdbd084c04bd.png)

It's defintely tier_REUTLINGEN so you need to change this here.

2021-10-22 09:20 UTC, hbruch commented on app/configurations/config.landstadtmobil.js
> +            'tier-reutlingen': {
I tested against current prod, which was an older version. Besides this, there was an issue with upper/lower case wich is now fixed

2021-10-25 09:08 UTC, merged