refactor(itinerary): adapt itinerary-page component to upstream
stadtnavi/digitransit-ui pull request #826
Opened 2024-11-25 11:26 UTC by andreashelms

Apply upstream refactorings to itinerary-page component and sub components

2024-12-01 08:01 UTC, hbruch requested changes
Could you please check ItineraryListContainer? I think we should keep parkAndRide, Scooter and OnDemandTaxi.

Rest looks find to me, Thx!

2024-12-01 08:01 UTC, hbruch commented on app/component/ItineraryListContainer.js
> -      onDemandTaxi,
I dont't think we should remove these stadtnavi additions.

2024-12-01 08:01 UTC, hbruch commented on app/component/ItineraryListContainer.js
> -          onDemandTaxi={onDemandTaxi}
We should not remove stadtnavi additions

2024-12-02 14:23 UTC, andreashelms commented on app/component/ItineraryListContainer.js
> -      onDemandTaxi,
These props were not used in that component at all.

2024-12-02 14:24 UTC, andreashelms commented on app/component/ItineraryListContainer.js
> -          onDemandTaxi={onDemandTaxi}
Same here.

2024-12-05 16:55 UTC, hbruch approved these changes
Ok, we checked that scooters results are still provided. For OnDemand, even now herrenberg.stadtnavi.de shows no results, so this is unrelated to this change.

I approve this PR. Thx.

2024-12-09 10:54 UTC, merged